@startuml

'Skin
!include ./skin.pu

'MODULEs
actor "browser"
actor "PWA"

cloud "internet"

package "GCP" {
  node "API(Go)\nusing Cloud Run" as api {
  }

  node "APP(Vue)\nusing GAE" as app {
  }

  database "Postgres\nusing Cloud SQL" as db {
  }

  package "Batch" {
    node "Cloud Scheduler\nexecute am 00:00" as scheduler {
    }
    node "Cloud PubSub" as pubsub {
    }
    node "Cloud Functions" as function {
    }
  }
}

'RELATIONs
PWA -left-> internet
browser -right-> internet

internet --> app: Login & View memo list!
app -> api
api -> db

scheduler -> pubsub
pubsub -> function
function -up-> db : increase notified_cnt
@enduml
