@startuml
'MODULEs
node "raspberry pi" as pi {

  () "h2o(WEBserver)" as h2o

  node "Unicorn(APserver)" as unicorn {
    component "tag-mng App" as tag_mng_app
  }

  database "postgresql" as postgres {
    
  }

}

cloud "Internet" as internet {

}
cloud "GCP" as gcp {

}


'RELATIONs
internet - h2o
h2o - unicorn : :8777
unicorn - tag_mng_app
tag_mng_app -- postgres
postgres - gcp : backup/every6h

@enduml
