---
- hosts:
    - jobserver
  tasks:
    - name: Echo vars
      debug:
        msg: "Hello, {{ test_var }}... {{ dsn }}"

    - name: Deploy Hugo config.toml
      become: yes
      copy:
        src: config.toml
        dest: /home/lbfdeatq/newmemos/config.toml

    - name: Install pip3 & supervisor
      become: yes
      apt:
        name:
          - python3-pip
          - supervisor

    - name: Deploy exposer deamon supervisor's config
      become: yes
      template:
        src: exposer.conf.j2
        dest: /etc/supervisor/conf.d/exposer.conf

    - name: Manage process
      become: yes
      supervisorctl:
        name: exposer
        state: restarted
        config: /etc/supervisor/supervisord.conf
