package models

// Code generated by xo. DO NOT EDIT.

import (
	"context"
	"database/sql"
)

// MemoTag represents a row from 'public.memo_tag'.
type MemoTag struct {
	MemosID sql.NullInt64 `json:"memos_id"` // memos_id
	TagsID  sql.NullInt64 `json:"tags_id"`  // tags_id
}

// Memo returns the Memo associated with the MemoTag's (MemosID).
//
// Generated from foreign key 'memo_tag_memos_id_fkey'.
func (mt *MemoTag) Memo(ctx context.Context, db DB) (*Memo, error) {
	return MemoByID(ctx, db, int(mt.MemosID.Int64))
}

// Tag returns the Tag associated with the MemoTag's (TagsID).
//
// Generated from foreign key 'memo_tag_tags_id_fkey'.
func (mt *MemoTag) Tag(ctx context.Context, db DB) (*Tag, error) {
	return TagByID(ctx, db, int(mt.TagsID.Int64))
}
