# frozen_string_literal: true

# [重要]とりあえずWebアプリ起動
# https://qiita.com/k-ta-yamada/items/9e35c5f8b31862267e01

# bundle install後に躓いた時の対処(原因：bundle exec ruby 時のrubyのversion違い(path違い))
# https://qiita.com/white_aspara25/items/d5e19b82be17048d9215

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"
gem 'sinatra'
gem 'sinatra-contrib'

# NOTE: ！！unicorn は、WSLで使えないっぽい！！
gem 'unicorn'

gem 'pg'
